import Share from 'react-native-share';
import { Event } from '@/services/DatabaseService';
import { showToast } from './toast';

interface Attendee {
  name: string;
  checked_in: boolean;
}

export class ShareUtils {
  /**
   * Share event details
   */
  static async shareEvent(event: Event) {
    try {
      const message = `🎉 You're invited to ${event.title}!\n\n📅 Date: ${event.date}\n⏰ Time: ${event.time}\n📍 Location: ${event.location || 'TBA'}\n\n${event.notes ? `📝 ${event.notes}` : ''}`;
      
      await Share.open({
        title: `Event Invitation - ${event.title}`,
        message,
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      if (errorMessage !== 'User did not share') {
        console.error('Error sharing event:', error);
        showToast.error('Failed to share event');
      }
    }
  }

  /**
   * Share QR code image
   */
  static async shareQRCode(eventTitle: string, qrCodeUri: string) {
    try {
      await Share.open({
        title: `${eventTitle} - Check-in QR Code`,
        message: `Check-in QR code for ${eventTitle}`,
        url: qrCodeUri,
        type: 'image/png',
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      if (errorMessage !== 'User did not share') {
        console.error('Error sharing QR code:', error);
        showToast.error('Failed to share QR code');
      }
    }
  }

  /**
   * Share attendee list as text
   */
  static async shareAttendeeList(eventTitle: string, attendees: Attendee[]) {
    try {
      const attendeeList = attendees
        .map((attendee, index) => `${index + 1}. ${attendee.name}${attendee.checked_in ? ' ✅' : ''}`)
        .join('\n');
      
      const message = `📋 Attendee List - ${eventTitle}\n\n${attendeeList}\n\nTotal: ${attendees.length} attendees\nChecked in: ${attendees.filter(a => a.checked_in).length}`;
      
      await Share.open({
        title: `Attendee List - ${eventTitle}`,
        message,
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      if (errorMessage !== 'User did not share') {
        console.error('Error sharing attendee list:', error);
        showToast.error('Failed to share attendee list');
      }
    }
  }

  /**
   * Share statistics report
   */
  static async shareStats(stats: {
    totalEvents: number;
    totalAttendees: number;
    checkInRate: string;
    timeFilter: string;
  }) {
    try {
      const message = `Event Statistics Report\n\n Events: ${stats.totalEvents}\n👥 Total Attendees: ${stats.totalAttendees}\n✅ Check-in Rate: ${stats.checkInRate}%\n📅 Period: ${stats.timeFilter}\n\nGenerated by Ventry App`;
      
      await Share.open({
        title: 'Event Statistics Report',
        message,
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      if (errorMessage !== 'User did not share') {
        console.error('Error sharing stats:', error);
        showToast.error('Failed to share statistics');
      }
    }
  }

  /**
   * Share app download link
   */
  static async shareApp() {
    try {
      const message = ` Check out Ventry - the best event management app!\n\nManage events, track attendees, and generate QR codes easily.\n\n🔗 Download: [App Store/Play Store Link]`;
      
      await Share.open({
        title: 'Ventry - Event Management App',
        message,
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      if (errorMessage !== 'User did not share') {
        console.error('Error sharing app:', error);
        showToast.error('Failed to share app');
      }
    }
  }
}